make: 
	g++ utils.cpp path.cpp similarity_table.cpp similar_function_finder.cpp counter_duplication_code_trie.cpp counter_duplication_code.cpp similarity_explorer.cpp big_clone_formater.cpp function.cpp big_clone_tailor_evaluator.cpp orchestrator.cpp -o exec -ljsoncpp -g

breaker:
	g++ utils.cpp function_breaker.cpp -o breaker -ljsoncpp -g
