make: 
	g++ utils.cpp path.cpp similarity_table.cpp similar_function_finder.cpp counter_duplication_code_trie.cpp counter_duplication_code.cpp similarity_explorer.cpp function.cpp orchestrator.cpp -o exec -ljsoncpp -g
