var dir_6feaf498c9e73db348d38b85b50398b5 =
[
    [ "main.c", "current_2tmp_2source_2test__multiple__file__big__functions__against__small_2big_8c_2main_8c.html", "current_2tmp_2source_2test__multiple__file__big__functions__against__small_2big_8c_2main_8c" ],
    [ "sorted_by_distance_to_median.c", "current_2tmp_2source_2test__multiple__file__big__functions__against__small_2big_8c_2sorted__by__distance__to__median_8c.html", "current_2tmp_2source_2test__multiple__file__big__functions__against__small_2big_8c_2sorted__by__distance__to__median_8c" ]
];