var dir_a209593446b1b50c6db0449b74c9537f =
[
    [ "compute_dist_to_median.c", "current_2tmp_2source_2test__same__file__big__function__against__small_8c_2compute__dist__to__median_8c.html", "current_2tmp_2source_2test__same__file__big__function__against__small_8c_2compute__dist__to__median_8c" ],
    [ "compute_p.c", "current_2tmp_2source_2test__same__file__big__function__against__small_8c_2compute__p_8c.html", "current_2tmp_2source_2test__same__file__big__function__against__small_8c_2compute__p_8c" ],
    [ "compute_v_sorted.c", "current_2tmp_2source_2test__same__file__big__function__against__small_8c_2compute__v__sorted_8c.html", "current_2tmp_2source_2test__same__file__big__function__against__small_8c_2compute__v__sorted_8c" ],
    [ "main.c", "current_2tmp_2source_2test__same__file__big__function__against__small_8c_2main_8c.html", "current_2tmp_2source_2test__same__file__big__function__against__small_8c_2main_8c" ],
    [ "sorted_by_distance_of_median.c", "current_2tmp_2source_2test__same__file__big__function__against__small_8c_2sorted__by__distance__of__median_8c.html", "current_2tmp_2source_2test__same__file__big__function__against__small_8c_2sorted__by__distance__of__median_8c" ],
    [ "sorted_by_distance_to_median.c", "current_2tmp_2source_2test__same__file__big__function__against__small_8c_2sorted__by__distance__to__median_8c.html", "current_2tmp_2source_2test__same__file__big__function__against__small_8c_2sorted__by__distance__to__median_8c" ]
];