var dir_da3014b32e42c8fee9d1dc6b18c8817a =
[
    [ "compute_dist_to_median.c", "expected_2tmp_2source_2test__same__file__big__function__against__small_8c_2compute__dist__to__median_8c.html", "expected_2tmp_2source_2test__same__file__big__function__against__small_8c_2compute__dist__to__median_8c" ],
    [ "compute_p.c", "expected_2tmp_2source_2test__same__file__big__function__against__small_8c_2compute__p_8c.html", "expected_2tmp_2source_2test__same__file__big__function__against__small_8c_2compute__p_8c" ],
    [ "compute_v_sorted.c", "expected_2tmp_2source_2test__same__file__big__function__against__small_8c_2compute__v__sorted_8c.html", "expected_2tmp_2source_2test__same__file__big__function__against__small_8c_2compute__v__sorted_8c" ],
    [ "main.c", "expected_2tmp_2source_2test__same__file__big__function__against__small_8c_2main_8c.html", "expected_2tmp_2source_2test__same__file__big__function__against__small_8c_2main_8c" ],
    [ "sorted_by_distance_of_median.c", "expected_2tmp_2source_2test__same__file__big__function__against__small_8c_2sorted__by__distance__of__median_8c.html", "expected_2tmp_2source_2test__same__file__big__function__against__small_8c_2sorted__by__distance__of__median_8c" ],
    [ "sorted_by_distance_to_median.c", "expected_2tmp_2source_2test__same__file__big__function__against__small_8c_2sorted__by__distance__to__median_8c.html", "expected_2tmp_2source_2test__same__file__big__function__against__small_8c_2sorted__by__distance__to__median_8c" ]
];